[package]
name = "gauth"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
totp-rs = { version = "5.7", features = ["qr", "serde"] }
keyring = "3.6"
aes-gcm = "0.10"
argon2 = "0.5"
dialoguer = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9.2"
qr2term = "0.3.3"
indicatif = "0.18.3"
base32 = "0.5.1"

