[package]
name = "gauth"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
dialoguer = "0.12.0"
keyring = { version = "3.6.3", features = ["apple-native", "windows-native", "linux-native"] }
thiserror = "1.0"
